# Generated by Django 5.0 on 2023-12-17 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publishers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publisher',
            name='country',
            field=models.CharField(max_length=2),
        ),
    ]
